### ISSUE TITLE
Escape twitter commands from status update

### ISSUE THREAD

**Issue by jonaslund** [reneraab/node-twitter-api#24]
```
    twitter.statuses("update", {
            status: tweet
        },
```
If tweet starts with the charachter d or m, the api tries to direct message someone. Is there a quick and easy way to disable all of that functionality with the update function and only have it post status updates. Ie, how can I post updates that starts with d or m, that doesn't tries to send direct messages.

**Comment by reneraab** [comment]
I don't think you can. At least I did not find anything concerning your question in the Twitter API documentation.
