### ISSUE TITLE
Any support for x_auth_access_type for getRequestToken function?

### ISSUE THREAD

**Issue by b4x** [reneraab/node-twitter-api#29]
The optional x_auth_access_type parameter allows an application request to be downgraded from write access to read only access.
https://dev.twitter.com/oauth/reference/post/oauth/request_token

I tried adding the parameter to the 'var Twitter' constructor something like this in twitter.js

this.callback = options.callback;
this.x_auth_access_type = options.x_auth_access_type;
this.oa = new oauth.OAuth("https://twitter.com/oauth/request_token", "https://twitter.com/oauth/access_token", this.consumerKey, this.consumerSecret, "1.0A", this.callback, "HMAC-SHA1", this.x_auth_access_type);

and then making a request with 

readAccess = new twitterAPI({
			consumerKey: key,
			consumerSecret: secret,
		        callback: url,
                        x_auth_access_type: 'read'});

but I'm unsure how to encode it and due to the lack of documentation from Twitter it might even be due to not being part of the oauth npm package.

**Comment by reneraab** [comment]
I found a way to add what you asked for. You just need to specify x_auth_access_type in the constructor (see README.md). I will push it to npm shortly.
