### ISSUE TITLE
Call to Twitter.uploadMedia() returns "media type unrecognized."

### ISSUE THREAD

**Issue by BlazeSahlzen** [reneraab/node-twitter-api#33]
I am getting `{error:"media type unrecognized."}` in the `body` parameter of the callback inside `uploadMedia()` function. This is happening for both `isBase64:true` and `isBase64:false`. Please look into it.

**Comment by reneraab** [comment]
From the information you have given, I cannot reproduce your problem. Could you please give a bit more information about the stuff you tried? The type of the image, the code that you used to call the function, etc.

**Comment by BlazeSahlzen** [comment]
Solved it. I was mistakenly adding `data:image/jpeg;base64,` before the image string. Once I removed it, the upload worked just fine.
