### ISSUE TITLE
error on trying to get request token

### ISSUE THREAD

**Issue by mjseyyedi** [reneraab/node-twitter-api#39]
I'm using this package to get request token and access token.
but when I call for request token , I get the error below

> 
> Error getting OAuth request token :  { statusCode: 401,
>   data: '<?xml version="1.0" encoding="UTF-8"?>\n<hash>\n  <error>Desktop applications only support the oauth_callback v
> alue \'oob\'</error>\n  <request>/oauth/request_token</request>\n</hash>\n' }
>
> 

and here is code:

```
twitterAPI = require('node-twitter-api');
 function setSettingForTwitter(request, response, sessionManager) {
        var twitter = new twitterAPI({
            consumerKey: '1YTLohgHVA9L2Mri0bM2692Rl',
            consumerSecret: 'sGlYSxrs1uhS7v8qGY5fb2S8xLeNT2nACmchpONcjHO0bMfmzo',
            callback: 'http://localhost.com/app/socialNetworkSetting/respondFromTwitter'
        });


    twitter.getRequestToken(function(error, requestToken, requestTokenSecret, results){
        if (error) {
            console.log("Error getting OAuth request token : " , error);
        } else {
            //store token and tokenSecret somewhere, you'll need them later; redirect user
        }
    }); }
```

**Comment by reneraab** [comment]
You have to set a callback value in the Twitter Developer app settings (the same URL that you use in your code). Otherwise Twitter thinks that you want to have a desktop application which does not use callbacks. BTW: This was the first result of a simple Google search, so please try that first in the future.
