### ISSUE TITLE
Interested in an overhaul?

### ISSUE THREAD

**Issue by isaachinman** [reneraab/node-twitter-api#53]
Hi there, wondering if the maintainer(s) of this repo are interested in an overhaul PR. I recently forked this project and converted it from OO/callbacks to functional/promises.

Seeing as this repo is no longer maintained, just wanted to ask if you're open to breathing in some new life. Otherwise I'll just fork it and put my updates there. Let me know!

**Comment by reneraab** [comment]
Sadly, I don't have the time and interest/knowledge in node.js at the moment. So go ahead and make a fork :)

**Comment by isaachinman** [comment]
Okay, no worries. I'm interested in actively maintaining this project, so at some point in the future it might be nice to point new users toward that fork.
